version: "3"
services:
  APP:
    container_name: frontend_run
    image: segiraldovi/my_front
    ports:
      - 4200:4200
    environment:
      - API_URL=api
      - API_PORT=8081
    depends_on:
      - api

  api:
    container_name: backend_run
    image: segiraldovi/my_back
    ports:
      - 8081:8081
    environment:
      - DB_URL=postgres
      - POSTGRES_PORT=5432

  postgres:
    container_name: postgres_sql
    image: postgres
    ports:
      - 5432:5432
    enviroment:
      - POSTGRES_PASSWORD=secret