version: "3"
services:
  APP:
    container_name: frontend
    image: segiraldovi/my_front
    ports:
      - 4200:4200
    environment:
      - API_URL=api
      - API_PORT=8081
    depends_on:
      - api

  api:
    container_name: backend
    image: segiraldovi/my_back
    ports:
      - 8081:8081
    environment:
      - DB_URL=group5-rds.cqqmj66dxtlw.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432